### ISSUE TITLE
Timer STM32 #error This code is designed to run on STM32F/L/H/G/WB/MP1 platform!  Please check your Tools->Board setting.

### ISSUE THREAD

**Issue by soheilpaper** [khoih-prog/TimerInterrupt_Generic#2]
I have installed the library of **[TimerInterrupt_Generic][1]** for ArduinoSTM32 module via Arduino IDE, so i have tried to test the example of library as you can see below:

[![enter image description here][2]][2]
and i have gotten this error:

```



TimerInterruptLEDDemo:45:4: error: #error This code is designed to run on STM32F/L/H/G/WB/MP1 platform! Please check your Tools->Board setting.
   #error This code is designed to run on STM32F/L/H/G/WB/MP1 platform! Please check your Tools->Board setting.
    ^
In file included from /home/so/snap/arduino/current/Arduino/libraries/TimerInterrupt_Generic/examples/STM32/TimerInterruptLEDDemo/TimerInterruptLEDDemo.ino:64:0:
/home/so/snap/arduino/current/Arduino/libraries/TimerInterrupt_Generic/src/TimerInterrupt_Generic.h:86:4: error: #error Unsupported Board! Please check your Tools->Board setting.
   #error Unsupported Board! Please check your Tools->Board setting.
    ^
exit status 1
#error This code is designed to run on STM32F/L/H/G/WB/MP1 platform! Please check your Tools->Board setting.

```
Also, This question is asked here:
https://arduino.stackexchange.com/questions/79638/timer-stm32-error-this-code-is-designed-to-run-on-stm32f-l-h-g-wb-mp1-platform

  [1]: https://github.com/khoih-prog/TimerInterrupt_Generic/
  [2]: https://i.stack.imgur.com/lS38R.jpg

**Comment by khoih-prog** [comment]
Check [STM32_TimerInterrupt Library Error](https://github.com/khoih-prog/STM32_TimerInterrupt/issues/1)

> The [**Roger Clark's STM32 core**](https://github.com/rogerclarkmelbourne/Arduino_STM32)  you're using is not currently supported. I don't know in the future if I can add that core into the supported list.
> 
> You have to use this [**Arduino_Core_STM32**](https://github.com/stm32duino/Arduino_Core_STM32).
> 
> Convert to new core by following the intructions in [**Getting Started**](https://github.com/stm32duino/Arduino_Core_STM32#getting-started)
