### ISSUE TITLE
PlatformIO and Heltec WiFi LoRa V2

### ISSUE THREAD

**Issue by MicSchi** [khoih-prog/TimerInterrupt_Generic#5]
### Describe the bug

Seems i cannot make it compile because it cannot find some function. Googling for it does not reveal any help. I have no idea how to overcome this issue.

- timer_isr_callback_add 
- TIMER_INTR_T0
- TIMER_INTR_T1

### Steps to Reproduce

Visual Studio Code 1.63.2 + PlatformIO Core 5.2.4. + ESP32 + #include "TimerInterrupt_Generic.h"

### Expected behavior

Compile successfully

### Actual behavior
Terminal output when compiling

Processing heltec_wifi_lora_32_V2 (platform: espressif32; board: heltec_wifi_lora_32_V2; framework: arduino)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/heltec_wifi_lora_32_V2.html
PLATFORM: Espressif 32 (3.4.0) > Heltec WiFi LoRa 32 (V2)
HARDWARE: ESP32 240MHz, 320KB RAM, 8MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-arduinoespressif32 3.10006.210326 (1.0.6)
 - tool-esptoolpy 1.30100.210531 (3.1.0)
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ strict
Found 45 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Heltec ESP32 Dev-Boards> 1.1.0
|   |-- <SPI> 1.0
|   |-- <Wire> 1.0.1
|-- <TimerInterrupt_Generic> 1.8.0
|-- <DHT sensor library for ESPx> 1.18
|-- <Freenove WS2812 Lib for ESP32> 1.0.5
|-- <SPI> 1.0
|-- <U8g2> 2.31.2
|   |-- <SPI> 1.0
|   |-- <Wire> 1.0.1
|-- <Wire> 1.0.1
|-- <Ai Esp32 Rotary Encoder> 1.4
Building in release mode
Compiling .pio\build\heltec_wifi_lora_32_V2\src\WeckerDeluxe.cpp.o
In file included from .pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/TimerInterrupt_Generic.h:221:0,
                 from src\WeckerDeluxe.cpp:38:
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:90:22: warning: "/*" within comment [-Wcomment]
   TIMER_GROUP_0 = 0, /*!<Hw timer group 0
                      ^
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:91:22: warning: "/*" within comment [-Wcomment]
   TIMER_GROUP_1 = 1, /*!<Hw timer group 1
                      ^
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:100:16: warning: "/*" within comment [-Wcomment]
   TIMER_0 = 0, /*!<Select timer0 of GROUPx
                ^
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:101:16: warning: "/*" within comment [-Wcomment]
   TIMER_1 = 1, /*!<Select timer1 of GROUPx
                ^
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8g2_message.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8g2_polygon.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8g2_selection_list.c.o
In file included from .pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/TimerInterrupt_Generic.h:221:0,
                 from src\WeckerDeluxe.cpp:38:
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h: In member function 'bool ESP32TimerInterrupt::setFrequency(float, esp32_timer_callback)':
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:307:100: error: 'timer_isr_callback_add' was not declared in this scope     
         timer_isr_callback_add(_timerGroup, _timerIndex, _callback, (void *) (uint32_t) _timerNo, 0);
                                                                                                    ^
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h: In member function 'void ESP32TimerInterrupt::detachInterrupt()':
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:349:66: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                  ^
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:349:82: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                  ^
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h: In member function 'void ESP32TimerInterrupt::disableTimer()':
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:358:66: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                  ^
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:358:82: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_disable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                  ^
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h: In member function 'void ESP32TimerInterrupt::reattachInterrupt()':        
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:368:65: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                 ^
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:368:81: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                 ^
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h: In member function 'void ESP32TimerInterrupt::enableTimer()':
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:378:65: error: 'TIMER_INTR_T0' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                 ^
.pio\libdeps\heltec_wifi_lora_32_V2\TimerInterrupt_Generic\src/ESP32TimerInterrupt_Generic.h:378:81: error: 'TIMER_INTR_T1' was not declared in this scope
       timer_group_intr_enable(_timerGroup, (_timerIndex == 0) ? TIMER_INTR_T0 : TIMER_INTR_T1);
                                                                                 ^
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8g2_setup.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8log.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8log_u8g2.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8log_u8x8.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_8x8.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_byte.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_cad.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_capture.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_a2printer.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_hd44102.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_il3820_296x128.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_ist3020.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_ist7920.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_ks0108.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_lc7981.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_ld7032_60x32.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_ls013b7dh03.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_max7219.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_pcd8544_84x48.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_pcf8812.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_pcf8814_hx1230.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_s1d15721.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_s1d15e06.c.o
C:\Users\mic\Documents\Arduino\libraries\U8g2\src\clib\u8x8_d_s1d15721.c: In function 'u8x8_d_s1d15721_common':
C:\Users\mic\Documents\Arduino\libraries\U8g2\src\clib\u8x8_d_s1d15721.c:71:14: warning: variable 'y' set but not used [-Wunused-but-set-variable]
   uint8_t x, y, c;
              ^
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_sbn1661.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_sed1330.c.o
Compiling .pio\build\heltec_wifi_lora_32_V2\libda1\U8g2\clib\u8x8_d_sh1106_64x32.c.o
*** [.pio\build\heltec_wifi_lora_32_V2\src\WeckerDeluxe.cpp.o] Error 1

### Information

Please ensure to specify the following:
Visual Studio Code 1.63.2 + PlatformIO Core 5.2.4. + ESP32
* Platform.io Core 5.2.4.
* `ESP32` (heltecautomation/Heltec ESP32 Dev-Boards@^1.1.0)
* Windows 10 64bit
  
### Example

```
#if !defined( ESP32 )
  #error This code is intended to run on the ESP32 platform! Please check your Tools->Board setting.
#endif

#include "Arduino.h"
#include "heltec.h"   // WiFi LoRa 32 (V2)

// The Timer for the different things
// These define's must be placed at the beginning before #include "ESP32_New_TimerInterrupt.h"
// _TIMERINTERRUPT_LOGLEVEL_ from 0 to 4
#define _TIMERINTERRUPT_LOGLEVEL_     0
#include "TimerInterrupt_Generic.h"

```

### Additional context

; platformio.ini
[env:heltec_wifi_lora_32_V2]
platform = espressif32
board = heltec_wifi_lora_32_V2
board_build.mcu = esp32
board_build.f_cpu = 240000000L
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
upload_port = COM8
lib_compat_mode = strict
lib_deps = 
	heltecautomation/Heltec ESP32 Dev-Boards@^1.1.0
	khoih-prog/TimerInterrupt_Generic@^1.8.0

**Comment by MicSchi** [comment]
Just tested with Arduino IDE 1.8.16 and Example -> TimerInterrupt_Generic -> ESP32 -> Argument_None resulting in the same error messages.

**Comment by khoih-prog** [comment]
> framework-arduinoespressif32 3.10006.210326 (1.0.6)

Please read [**Prerequisites**](https://github.com/khoih-prog/TimerInterrupt_Generic#prerequisites), and **update ESP32 core to v2.0.1+** to avoid wasting everybody's time

![Selection_088](https://user-images.githubusercontent.com/57012152/147289991-1c79587c-c3a8-4a2b-8444-f10ee8b0ddc8.png)

**Comment by MicSchi** [comment]
Thank you for your fast answer, it is very much apprechiated! It help me to get further with the topic after beeing stuck for nearly a day. Didn't intent to waste anybodys time. Just new to ESP32 topic and overloaded by the massive amount of information available.

Maybe interesting for others: It seems that the Heltec board is tight to the v1.0.6 at the moment. Installing esp32 V2.0.2 does not improve the situation. Update wasn't possible because wasn't installed before. 
I assume espressif v1.0.6 is integral part of the Heltec board package and to utilize ESP v2.0.2 package I would need to switch to one of its supported boards. 
![image](https://user-images.githubusercontent.com/90507397/147348958-5de21cfa-bfee-4692-aef4-0e8c66d6fb73.png)
It seems the Heltec package needs changes to incorporate espressif v2.0.1+. Therefore I added a comment to an existing comparable issue there: [Heltec-Aaron-Lee/WiFi_Kit_series](https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/issues/150)
