### ISSUE TITLE
Use of the code should be more generic cross-platform.

### ISSUE THREAD

**Issue by acwest** [khoih-prog/TimerInterrupt_Generic#6]
It appears from the examples that even with the generic wrapper, the code still needs to be written to be quite specific to the platform. It should be possible , for at least simple cases, to be able to structure it in a way that the library can be used in a way where it requires no changes to compile and run on different platforms. There are, of course, challenges, as the different platforms have very different internal implementations...
I am starting on implementing this, but would like to discuss some of the things I have noticed in the current implementation that could cause issues with my ideas...

**Comment by khoih-prog** [comment]
HI @acwest 

Thanks for your interest in the library.

It was written for Arduino IDE. To use in other platforms, the user is assumed to have enough knowledge to convert. This is a simple job and sometimes can be done automatically by the platform, e.g. PlatformIO.

Good Luck,
